---
title: "Downloading Climate data"
author: "Jackie"
date: "2025-03-28"
runtime: shiny
output: html_document
---

```{r setup_install and load packages, include=FALSE}
#install.packages("SWTools")
library(SWTools)
library(readr)
library(DT)
#library(shiny)
```

## Select sites to download and parameters



```{r list of sites, include=FALSE}

# creating a data frame
list_of_sites <- data.frame(
    Name = c("Karoonda", "Wharminda", "Copeville", "Walpeup" , "Bute", "Balaklava", "Annuello"), ### add more here when you have the info
    Number = c("25006", "18113", "25003", "76065", "21012", "21002", "76000"),
    Latitude = c("-35.09", "-33.97", "-34.80", "-35.14",  "-33.86", "-34.14", "-34.85"),
    Longitude = c("139.90", "136.25", "139.85", "142.02", "138.01", "138.42", "142.78"),
    State = c("SA", "SA", "SA", "VIC","SA", "SA", "VIC")
    )

```

```{r display sites, echo=FALSE}
datatable(list_of_sites)

```
```{r eval=FALSE, include=FALSE}

#https://epirhandbook.com/new_pages/flexdashboard.html
selectInput(inputId="site", 
            label = "Select site:",
              choices = c(c("Karoonda", "Wharminda", "Copeville", "Walpeup" , "Bute", "Balaklava", "Annuello")), 
            selected = "Karoonda")


```
```{r user_set_parameters, eval=FALSE, include=FALSE}
# savedFilterValues <- reactiveVal()
#   data <- reactive({
#     get(input$site)
```    
    

## Download or update SILO patchpoint using SWTool package
https://www.rdocumentation.org/packages/SWTools/versions/1.1.0/topics/SILODownload


* This package download the file/s and saves it as text file with the name of the station
* Here I have the files saved to  "H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files"
* Last day of data, in the format "YYYYMMDD". Will default to yesterday if not specified



```{r Download_parameters, eval=FALSE, include=FALSE}

Site_number <- "25006"
email_jackie <-"jackie.ouzman@csiro.au"
START <- "19000101"
#FINISH <- "20050203"
Files_saved <- "H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files"


## this will download patchpoint data and save it to file directory that is specified
SILODownload(
  #SiteList= Site_number,
  SiteList = c("25006" ,"18113", "25003" ,"76065" ,"21012" ,"21002", "76000"),
  username = email_jackie,
  password = "gui",
  path = Files_saved,
  startdate = START,
  enddate = , 
  ssl = FALSE
)

```

```{r clean_files 25006, include=FALSE}
#Karoonda
station_number <- "25006"
Files_saved <- "H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/"

df <- read_table(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"),
  col_types =   cols(`Date2` = col_date(format = "%d-%m-%Y"),
  `Day` =   col_number()  ,
  `Radn` = col_number(),
  `T.Max` = col_number(),
  `T.Min` = col_number(),    
  `Rain` = col_number(),     
  `Evap` = col_number(), 
  `VP` = col_number()),
        skip = 51
      )
head(df)

#remove first row
df <- df %>% dplyr::filter( Date != "(yyyymmdd)")
head(df)

# select clms
names(df)
df <- df %>%  dplyr::select(Date  ,
                                     Day ,
                                     Date2 ,
                                     T.Max ,
                                     T.Min ,  
                                     Rain ,  
                                     Evap   ,
                                     Radn )

df <- df %>% 
  dplyr::rename(day_of_year = Day,
         Date_string = Date,
         Date = Date2
         ) %>% 
  dplyr::mutate(year = lubridate::year(Date),
         month =lubridate::month(Date),
         day_of_month = lubridate::day(Date),
         month_name = lubridate::month(Date, label = TRUE)
  )
str(df)

df_date_download <- read_csv(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"), 
  col_names = FALSE, skip = 15) %>% dplyr::slice_head()
df_date_download$X1

df_date_download$X1 <- gsub('[^[:alnum:] ]', '', df_date_download$X1)
df_date_download$X1 <- gsub(" Extracted from SILO BoM Only dataset on " , '', df_date_download$X1)
df_date_download$X1





  
df <- df %>% dplyr::mutate(Number = station_number)
df<- dplyr::left_join(df,list_of_sites)

df <- df
write_csv(df,
          file = paste0(Files_saved,"Neater_file_",station_number,".csv"))



```


```{r clean_files 18113, include=FALSE}
#Wharminda
station_number <- "18113"
Files_saved <- "H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/"

rm(df)
df <- read_table(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"),
  col_types =   cols(`Date2` = col_date(format = "%d-%m-%Y"),
  `Day` =   col_number()  ,
  `Radn` = col_number(),
  `T.Max` = col_number(),
  `T.Min` = col_number(),    
  `Rain` = col_number(),     
  `Evap` = col_number(), 
  `VP` = col_number()),
        skip = 51
      )
head(df)

#remove first row
df <- df %>% dplyr::filter( Date != "(yyyymmdd)")
head(df)

# select clms
names(df)
df <- df %>%  dplyr::select(Date  ,
                                     Day ,
                                     Date2 ,
                                     T.Max ,
                                     T.Min ,  
                                     Rain ,  
                                     Evap   ,
                                     Radn )

df <- df %>% 
  dplyr::rename(day_of_year = Day,
         Date_string = Date,
         Date = Date2
         ) %>% 
  dplyr::mutate(year = lubridate::year(Date),
         month =lubridate::month(Date),
         day_of_month = lubridate::day(Date),
         month_name = lubridate::month(Date, label = TRUE)
  )
str(df)

df_date_download <- read_csv(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"), 
  col_names = FALSE, skip = 15) %>% dplyr::slice_head()
df_date_download$X1

df_date_download$X1 <- gsub('[^[:alnum:] ]', '', df_date_download$X1)
df_date_download$X1 <- gsub(" Extracted from SILO BoM Only dataset on " , '', df_date_download$X1)
df_date_download$X1





  
df <- df %>% dplyr::mutate(Number = station_number)
df<- dplyr::left_join(df,list_of_sites)


write_csv(df,
          file = paste0(Files_saved,"Neater_file_",station_number,".csv"))



```


```{r clean_files 25003, include=FALSE}
#Copeville
station_number <- "25003"
Files_saved <- "H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/"

rm(df)
df <- read_table(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"),
  col_types =   cols(`Date2` = col_date(format = "%d-%m-%Y"),
  `Day` =   col_number()  ,
  `Radn` = col_number(),
  `T.Max` = col_number(),
  `T.Min` = col_number(),    
  `Rain` = col_number(),     
  `Evap` = col_number(), 
  `VP` = col_number()),
        skip = 51
      )
head(df)

#remove first row
df <- df %>% dplyr::filter( Date != "(yyyymmdd)")
head(df)

# select clms
names(df)
df <- df %>%  dplyr::select(Date  ,
                                     Day ,
                                     Date2 ,
                                     T.Max ,
                                     T.Min ,  
                                     Rain ,  
                                     Evap   ,
                                     Radn )

df <- df %>% 
  dplyr::rename(day_of_year = Day,
         Date_string = Date,
         Date = Date2
         ) %>% 
  dplyr::mutate(year = lubridate::year(Date),
         month =lubridate::month(Date),
         day_of_month = lubridate::day(Date),
         month_name = lubridate::month(Date, label = TRUE)
  )
str(df)

df_date_download <- read_csv(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"), 
  col_names = FALSE, skip = 15) %>% dplyr::slice_head()
df_date_download$X1

df_date_download$X1 <- gsub('[^[:alnum:] ]', '', df_date_download$X1)
df_date_download$X1 <- gsub(" Extracted from SILO BoM Only dataset on " , '', df_date_download$X1)
df_date_download$X1





  
df <- df %>% dplyr::mutate(Number = station_number)
df<- dplyr::left_join(df,list_of_sites)


write_csv(df,
          file = paste0(Files_saved,"Neater_file_",station_number,".csv"))



```


```{r clean_files 76065, include=FALSE}
#Walpeup
station_number <- "76065"
Files_saved <- "H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/"

rm(df)
df <- read_table(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"),
  col_types =   cols(`Date2` = col_date(format = "%d-%m-%Y"),
  `Day` =   col_number()  ,
  `Radn` = col_number(),
  `T.Max` = col_number(),
  `T.Min` = col_number(),    
  `Rain` = col_number(),     
  `Evap` = col_number(), 
  `VP` = col_number()),
        skip = 51
      )
head(df)

#remove first row
df <- df %>% dplyr::filter( Date != "(yyyymmdd)")
head(df)

# select clms
names(df)
df <- df %>%  dplyr::select(Date  ,
                                     Day ,
                                     Date2 ,
                                     T.Max ,
                                     T.Min ,  
                                     Rain ,  
                                     Evap   ,
                                     Radn )

df <- df %>% 
  dplyr::rename(day_of_year = Day,
         Date_string = Date,
         Date = Date2
         ) %>% 
  dplyr::mutate(year = lubridate::year(Date),
         month =lubridate::month(Date),
         day_of_month = lubridate::day(Date),
         month_name = lubridate::month(Date, label = TRUE)
  )
str(df)

df_date_download <- read_csv(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"), 
  col_names = FALSE, skip = 15) %>% dplyr::slice_head()
df_date_download$X1

df_date_download$X1 <- gsub('[^[:alnum:] ]', '', df_date_download$X1)
df_date_download$X1 <- gsub(" Extracted from SILO BoM Only dataset on " , '', df_date_download$X1)
df_date_download$X1





  
df <- df %>% dplyr::mutate(Number = station_number)
df<- dplyr::left_join(df,list_of_sites)


write_csv(df,
          file = paste0(Files_saved,"Neater_file_",station_number,".csv"))



```


```{r clean_files 21012, include=FALSE}
#Bute
station_number <- "21012"
Files_saved <- "H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/"

rm(df)
df <- read_table(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"),
  col_types =   cols(`Date2` = col_date(format = "%d-%m-%Y"),
  `Day` =   col_number()  ,
  `Radn` = col_number(),
  `T.Max` = col_number(),
  `T.Min` = col_number(),    
  `Rain` = col_number(),     
  `Evap` = col_number(), 
  `VP` = col_number()),
        skip = 51
      )
head(df)

#remove first row
df <- df %>% dplyr::filter( Date != "(yyyymmdd)")
head(df)

# select clms
names(df)
df <- df %>%  dplyr::select(Date  ,
                                     Day ,
                                     Date2 ,
                                     T.Max ,
                                     T.Min ,  
                                     Rain ,  
                                     Evap   ,
                                     Radn )

df <- df %>% 
  dplyr::rename(day_of_year = Day,
         Date_string = Date,
         Date = Date2
         ) %>% 
  dplyr::mutate(year = lubridate::year(Date),
         month =lubridate::month(Date),
         day_of_month = lubridate::day(Date),
         month_name = lubridate::month(Date, label = TRUE)
  )
str(df)

df_date_download <- read_csv(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"), 
  col_names = FALSE, skip = 15) %>% dplyr::slice_head()
df_date_download$X1

df_date_download$X1 <- gsub('[^[:alnum:] ]', '', df_date_download$X1)
df_date_download$X1 <- gsub(" Extracted from SILO BoM Only dataset on " , '', df_date_download$X1)
df_date_download$X1





  
df <- df %>% dplyr::mutate(Number = station_number)
df<- dplyr::left_join(df,list_of_sites)


write_csv(df,
          file = paste0(Files_saved,"Neater_file_",station_number,".csv"))



```

```{r clean_files 21002, include=FALSE}
#Balaklava
station_number <- "21002"
Files_saved <- "H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/"

rm(df)
df <- read_table(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"),
  col_types =   cols(`Date2` = col_date(format = "%d-%m-%Y"),
  `Day` =   col_number()  ,
  `Radn` = col_number(),
  `T.Max` = col_number(),
  `T.Min` = col_number(),    
  `Rain` = col_number(),     
  `Evap` = col_number(), 
  `VP` = col_number()),
        skip = 51
      )
head(df)

#remove first row
df <- df %>% dplyr::filter( Date != "(yyyymmdd)")
head(df)

# select clms
names(df)
df <- df %>%  dplyr::select(Date  ,
                                     Day ,
                                     Date2 ,
                                     T.Max ,
                                     T.Min ,  
                                     Rain ,  
                                     Evap   ,
                                     Radn )

df <- df %>% 
  dplyr::rename(day_of_year = Day,
         Date_string = Date,
         Date = Date2
         ) %>% 
  dplyr::mutate(year = lubridate::year(Date),
         month =lubridate::month(Date),
         day_of_month = lubridate::day(Date),
         month_name = lubridate::month(Date, label = TRUE)
  )
str(df)

df_date_download <- read_csv(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"), 
  col_names = FALSE, skip = 15) %>% dplyr::slice_head()
df_date_download$X1

df_date_download$X1 <- gsub('[^[:alnum:] ]', '', df_date_download$X1)
df_date_download$X1 <- gsub(" Extracted from SILO BoM Only dataset on " , '', df_date_download$X1)
df_date_download$X1





  
df <- df %>% dplyr::mutate(Number = station_number)
df<- dplyr::left_join(df,list_of_sites)


write_csv(df,
          file = paste0(Files_saved,"Neater_file_",station_number,".csv"))



```


```{r clean_files 76000, include=FALSE}
#Annuello
station_number <- "76000"
Files_saved <- "H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/"

rm(df)
df <- read_table(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"),
  col_types =   cols(`Date2` = col_date(format = "%d-%m-%Y"),
  `Day` =   col_number()  ,
  `Radn` = col_number(),
  `T.Max` = col_number(),
  `T.Min` = col_number(),    
  `Rain` = col_number(),     
  `Evap` = col_number(), 
  `VP` = col_number()),
        skip = 51
      )
head(df)

#remove first row
df <- df %>% dplyr::filter( Date != "(yyyymmdd)")
head(df)

# select clms
names(df)
df <- df %>%  dplyr::select(Date  ,
                                     Day ,
                                     Date2 ,
                                     T.Max ,
                                     T.Min ,  
                                     Rain ,  
                                     Evap   ,
                                     Radn )

df <- df %>% 
  dplyr::rename(day_of_year = Day,
         Date_string = Date,
         Date = Date2
         ) %>% 
  dplyr::mutate(year = lubridate::year(Date),
         month =lubridate::month(Date),
         day_of_month = lubridate::day(Date),
         month_name = lubridate::month(Date, label = TRUE)
  )
str(df)

df_date_download <- read_csv(
  paste0("H:/Output-2/Analysis/Scripts/Jackie/Downloaded_files/",station_number,".txt"), 
  col_names = FALSE, skip = 15) %>% dplyr::slice_head()
df_date_download$X1

df_date_download$X1 <- gsub('[^[:alnum:] ]', '', df_date_download$X1)
df_date_download$X1 <- gsub(" Extracted from SILO BoM Only dataset on " , '', df_date_download$X1)
df_date_download$X1





  
df <- df %>% dplyr::mutate(Number = station_number)
df<- dplyr::left_join(df,list_of_sites)


write_csv(df,
          file = paste0(Files_saved,"Neater_file_",station_number,".csv"))



```