---
title: "Step 2 creating a decile table and assigning decile years"
author: "Jackie"
date: "2025-03-28"
output: html_document
runtime: shiny
---

```{r load_libary, include=FALSE}
library(ggplot2)
library(readxl)
library(tidyverse)
library(lubridate)
library(data.table)
library(stringr)
library(shiny)
```

## How to defined the start and end of growing season

```{r define start of GS, echo=FALSE}


numericInput(inputId="Day_start_GS_rainfall",
             label = "Day of the month that growing season rainfall starts:",
             value=1, min = 1, max = 31, step = 1)
numericInput(inputId="Month_start_GS_rainfall",
             label = "Month that  growing season rainfall starts:",
             value=4, min = 1, max = 12, step = 1)


```


```{r define end of GS, echo=FALSE}


numericInput(inputId="Day_end_GS_rainfall",
             label = "Day of the month that growing season rainfall ends:",
             value=15, min = 1, max = 31, step = 1)
numericInput(inputId="Month_end_GS_rainfall",
             label = "Month thatgrowing season rainfall ends:",
             value=10, min = 1, max = 12, step = 1)

```



```{r sites_selction_simple_version, echo=FALSE}
# creating a data frame
list_of_sites <- data.frame(
    Name = c("Karoonda", "Wharminda", "Copeville", "Walpeup" , "Bute", "Balaklava", "Annuello"), ### add more here when you have the info
    Number = c("25006", "18113", "25003", "76065", "21012", "21002", "76000"),
    Latitude = c("-35.09", "-33.97", "-34.80", "-35.14",  "-33.86", "-34.14", "-34.85"),
    Longitude = c("139.90", "136.25", "139.85", "142.02", "138.01", "138.42", "142.78"),
    State = c("SA", "SA", "SA", "VIC","SA", "SA", "VIC")
    )

selectInput(inputId="site_number", 
            label = "Select site number:",
              choices = (c("25006", "18113", "25003", "76065", "21012", "21002", "76000")), 
            selected = "25006")



```




```{r sites_selction_download, echo=FALSE}


### Display the top rows for the download the file for site selected

reactive_df_site_selection <- reactive({
      df <- read.csv(paste0(file.path("H:","Output-2", "Analysis", "Scripts", "Jackie", "Downloaded_files"), 
         "/Neater_file_",
         input$site_number, 
         ".csv")) 
     
      ## add a clm with two dates marked as start and end
      df <- df %>% mutate(
        start_end_GS_date = case_when(
          month ==input$Month_start_GS_rainfall & day_of_month == input$Day_start_GS_rainfall ~ "start_gs",
          month ==input$Month_end_GS_rainfall & day_of_month == input$Day_end_GS_rainfall ~ "end_gs",
      TRUE ~ NA))
      
      ### fill the blanks

      df <- df %>% fill(start_end_GS_date) %>%
      mutate(
      season = case_when(
      start_end_GS_date == "start_gs" ~ "gs",
      TRUE ~ "summer"))

      df <- df %>% select(-start_end_GS_date)
      
### can I add the summary here?

  })


# renderPrint({
#     print(names(reactive_df_site_selection()))
#   })
# renderPrint({
#     print(str(reactive_df_site_selection()))
#   })

```

#### Site name of file.
```{r sites_selction_reactive_version1, echo=FALSE}
## add reactive bit same as before but now we add a step to make the selection reactive - so it can be used in other function


# File site number and name
renderText({
    paste("You have selected site number", input$site_number,## this is the reactive call reactive()
          ".Which is ",
          distinct(reactive_df_site_selection(), Name)# get the name of the site user selected

          )
  })

```

#### Date range of file.
```{r sites_selction_reactive_version2, echo=FALSE}
## add reactive bit same as before but now we add a step to make the selection reactive - so it can be used in other function



#File start date and end date
renderText({
    paste("Start date in file is: ",
          min(reactive_df_site_selection()$Date),
           ". End date in file is: ",
          max(reactive_df_site_selection()$Date)
          )
  })

```







## Plot rain for each season type

```{r plot rain by season type, echo=FALSE}


renderPlot({
  reactive_df_site_selection() %>%
    group_by(year, season) %>%
    summarise(sum_rain_season = sum(Rain, na.rm = TRUE)) %>%
    
    
    ggplot(aes(x = year, y = sum_rain_season, fill = season)) +
    geom_bar(stat = "identity") +
    labs(
      title = "Sum of rain per year",
      subtitle = paste0(
        "Station name: ",
        distinct(reactive_df_site_selection(), Name)
      ),
      
       caption = paste0("Years included : ", 
                        year(min(reactive_df_site_selection()$Date)) , 
                        " to ", 
                        year(max(reactive_df_site_selection()$Date)), 
                           ". GS defined as: ", 
                        input$Day_start_GS_rainfall,"/",
                        input$Month_start_GS_rainfall, " to ",
                        input$Day_end_GS_rainfall, "/",
                        input$Month_end_GS_rainfall),
      
      y = "sum of rain")
})

```

## GS decile table 

```{r decile table GS, echo=FALSE}

DT::renderDT({

  
  gs_rain <- reactive_df_site_selection() %>%
    group_by(year, season) %>%
    summarise(sum_rain_season = sum(Rain, na.rm = TRUE)) %>%
    filter(season == "gs")
  
  ## 5a. GS ----------------------------------------------------------------------
#the percentiles for each year.

GS_decile_max_rain <- quantile(gs_rain$sum_rain_season, c(.1, .2, .3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0))
GS_deciles_names <- c("decile_1", "decile_2", "decile_3", "decile_4", "decile_5", "decile_6", "decile_7", "decile_8", "decile_9", "decile_10")

GS_decile_table <- data.frame(GS_decile_max_rain, GS_deciles_names, row.names = NULL)
GS_decile_table <- mutate(GS_decile_table, GS_decile_min_rain = lag(GS_decile_max_rain+0.1))


#add in the min value to table
GS_decile_table[1,3] <-  min(gs_rain$sum_rain_season)
GS_decile_table <- GS_decile_table %>%  select (GS_deciles_names, GS_decile_min_rain, GS_decile_max_rain)


 GS_decile_table <- GS_decile_table %>% 
   mutate(Station_name = distinct(reactive_df_site_selection(), Name),
          Station_number = input$site_number,
           Years_included = paste0(
                                   year(min(reactive_df_site_selection()$Date)) ,  " to ", 
                                   year(max(reactive_df_site_selection()$Date))),
          GS_period =   paste0(
                        input$Day_start_GS_rainfall,"/",
                        input$Month_start_GS_rainfall, " to ",
                        input$Day_end_GS_rainfall, "/",
                        input$Month_end_GS_rainfall)
          )
                         

GS_decile_table_df <- as.data.frame(GS_decile_table)
GS_decile_table_df <- GS_decile_table_df %>% mutate(across(where(is.numeric), round, 2))
#won't save because its reactive - I cant work it out

GS_decile_table_df
  
})
```


## Summer decile table 

```{r decile table Summer, echo=FALSE}

DT::renderDT({

  
  summer_rain <- reactive_df_site_selection() %>%
    group_by(year, season) %>%
    summarise(sum_rain_season = sum(Rain, na.rm = TRUE)) %>%
    filter(season == "summer")
  
  ## 5b. Summer ----------------------------------------------------------------------
#the percentiles for each year.

summer_decile_max_rain <- quantile(summer_rain$sum_rain_season, c(.1, .2, .3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0))
summer_deciles_names <- c("decile_1", "decile_2", "decile_3", "decile_4", "decile_5", "decile_6", "decile_7", "decile_8", "decile_9", "decile_10")

summer_decile_table <- data.frame(summer_decile_max_rain, summer_deciles_names, row.names = NULL)
summer_decile_table <- mutate(summer_decile_table, summer_decile_min_rain = lag(summer_decile_max_rain+0.1))


#add in the min value to table
summer_decile_table[1,3] <-  min(summer_rain$sum_rain_season)
summer_decile_table <- summer_decile_table %>%  select (summer_deciles_names, summer_decile_min_rain, summer_decile_max_rain)


 summer_decile_table <- summer_decile_table %>% 
   mutate(Station_name = distinct(reactive_df_site_selection(), Name),
          Station_number = input$site_number,
           Years_included = paste0(
                                   year(min(reactive_df_site_selection()$Date)) ,  " to ", 
                                   year(max(reactive_df_site_selection()$Date))),
          GS_period =   paste0(
                        input$Day_start_GS_rainfall,"/",
                        input$Month_start_GS_rainfall, " to ",
                        input$Day_end_GS_rainfall, "/",
                        input$Month_end_GS_rainfall)
          )
                         

summer_decile_table_df <- as.data.frame(summer_decile_table)
summer_decile_table_df <- summer_decile_table_df %>% mutate(across(where(is.numeric), round, 2))
#won't save because its reactive - I cant work it out

summer_decile_table_df
  
})
```